#!/usr/bin/perl
###############################################################################
# Copyright (C) 2006-2025 Jonathan Michaelson
#
# https://github.com/waytotheweb/scripts
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses>.
###############################################################################
# Added 2026-09-11 in https://github.com/nkyo/csf - see CHANGES.md.
#
# The unprivileged half of the wire: connects to csf-ui-helper's unix socket,
# sends one request, reads one response, and enforces the transport-level
# rules docs/WEBUI-RPC.md section 3 assumes the web tier already keeps.
#
# Two properties matter more than anything else in this file:
#
#   * ONE ATTEMPT, ALWAYS. There is no retry logic anywhere below, for any
#     operation, mutating or not. That is the simplest way to guarantee the
#     brief's "never retries a mutating operation": a client that never
#     retries at all cannot retry a mutating one by accident. A caller that
#     wants to offer the user a manual "try again" button is free to call
#     call() a second time with a fresh request id - this module just never
#     does it for them.
#   * A 10-second wall-clock budget covers connect, write and read together,
#     the way section 7's own "wall-clock deadline" language reads for the
#     helper side. Nothing here blocks past it, and nothing here retries past
#     it either - a slow or wedged helper gets one bounded attempt and a
#     synthesised error, never a hang. This includes connect() itself:
#     measured, a blocking AF_UNIX connect() to a listener whose backlog is
#     full does not return until the listener accepts - no timeout of its
#     own - and "16 children busy, 32 queued" (section 2, section 7) is a
#     reachable state, not a contrived one, especially with restart's 120s
#     child deadline holding a slot. _connect() below is non-blocking and
#     bounded by the same $deadline as everything else in this call.
#
# What this module returns is shaped exactly like a wire response (section
# 3.3: id, ok, and either data or error+message), whether the response really
# came over the socket or was synthesised locally because the socket could
# not be reached at all. A caller that only ever looks at ok/error/message/
# data therefore cannot tell the difference, which is the point: the error
# enumeration in section 3.5 is what the rest of this tier is built to
# understand, so a local failure is described in the same vocabulary rather
# than a second one nothing downstream knows how to read. E_UNAVAILABLE is
# used for "the socket could not be reached at all" (a structural precondition
# - nothing will succeed until someone fixes it, the same meaning section 3.5
# gives that code) and E_BACKEND for "it was reached but did not answer
# correctly or in time" (the same code section 3.5 uses for a backend that
# failed or ran out of time). Neither of these two local uses is a new wire
# error: they are this module's own best-effort re-use of a closed
# enumeration it does not get to extend (section 3.5's own words), applied to
# a failure the wire format has no other vocabulary for.
###############################################################################
package ConfigServer::UI::Client;

use strict;
use warnings;

use Fcntl ();
use Socket ();
use Time::HiRes ();
use ConfigServer::UI::Proto ();

our $VERSION = '1.00';

my $P = 'ConfigServer::UI::Proto';

our $DEFAULT_SOCKET_PATH = '/var/run/csf-ui/helper.sock';
our $DEFAULT_TIMEOUT     = 10;

###############################################################################
# Construction
#
# socket_path and timeout are the only knobs, and both exist for tests: a
# test can point this at a Unix-domain listener in a temp directory and use a
# short timeout instead of waiting out the real 10s to exercise the deadline
# path. Production code never overrides either.
###############################################################################
sub new {
	my ($class, %opt) = @_;
	return bless {
		socket_path => $opt{socket_path} || $DEFAULT_SOCKET_PATH,
		timeout     => defined $opt{timeout} ? $opt{timeout} : $DEFAULT_TIMEOUT,
	}, $class;
}

###############################################################################
# Request ids (section 3.2: "^[A-Za-z0-9._:-]{1,64}$ ... Generated by csf-ui").
#
# 16 bytes from /dev/urandom, rendered as 32 lowercase hex characters - the
# same shape docs/WEBUI-RPC.md section 4.8 uses for reconcile ids, and well
# inside the 64-byte cap. Exposed as its own method (rather than folded
# silently into call()) so a caller that needs to write its OWN access-log
# line with the same id the helper will see - the whole point of the join in
# section 8 - can generate the id first, log it, and then hand it to call().
###############################################################################
sub generate_id {
	my ($self) = @_;
	open(my $fh, '<', '/dev/urandom') or return undef;
	binmode($fh);
	my $bytes = '';
	while (length($bytes) < 16) {
		my $chunk;
		my $read = sysread($fh, $chunk, 16 - length($bytes));
		unless (defined $read && $read > 0) {
			close $fh;
			return undef;
		}
		$bytes .= $chunk;
	}
	close $fh;
	return unpack('H*', $bytes);
}

###############################################################################
# call($op, \%args, %opt) -> \%response
#
# %opt:
#   id => "..."   use this id instead of generating one. The caller is
#                 responsible for it being valid per section 3.2; an invalid
#                 one is treated as a local encode failure (E_INTERNAL) rather
#                 than sent, because a request this module cannot address is
#                 not this operation's problem to solve by guessing.
#
# Returns a hashref shaped like section 3.3: {id, ok, data} on success or
# {id, ok, error, message} on failure - including every locally-synthesised
# failure listed in the header comment above. This method never dies: a
# caller that only branches on $response->{ok} never needs an eval around it.
###############################################################################
sub call {
	my ($self, $op, $args, %opt) = @_;

	my $id = $opt{id};
	unless (defined $id) {
		$id = $self->generate_id;
		return _local_error(undef, 'E_INTERNAL', 'could not generate a request id')
			unless defined $id;
	}

	my $deadline = Time::HiRes::time() + $self->{timeout};

	my $line = eval {
		$P->can('encode')->({ op => $op, args => (defined $args ? $args : {}), id => $id });
	};
	return _local_error($id, 'E_INTERNAL', 'could not encode the request') unless defined $line;

	my ($socket, $error_kind, $connect_error) = _connect($self->{socket_path}, $deadline);
	unless ($socket) {
		# 'busy' (a non-blocking connect that never resolved before the
		# deadline - the full-backlog case measured above) maps to the same
		# transient/retry meaning section 3.5 gives E_BUSY. Every other
		# connect failure (no such socket, permission denied, connection
		# refused) is structural and maps to E_UNAVAILABLE, its existing
		# meaning here.
		my $code = (defined $error_kind && $error_kind eq 'busy') ? 'E_BUSY' : 'E_UNAVAILABLE';
		return _local_error($id, $code, "cannot reach csf-ui-helper: $connect_error");
	}

	unless (_write_all($socket, $line, $deadline)) {
		close $socket;
		return _local_error($id, 'E_BACKEND',
			'csf-ui-helper did not accept the request within the timeout');
	}

	my $response = eval { $P->can('read_message')->($socket, $deadline) };
	if (my $error = $@) {
		close $socket;
		if ($P->can('is_fault')->($error) && $error->{code} eq 'E_TIMEOUT') {
			return _local_error($id, 'E_BACKEND',
				'csf-ui-helper did not respond within the timeout');
		}
		my $message = $P->can('is_fault')->($error)
			? $error->{message}
			: 'csf-ui-helper sent a response this client could not read';
		return _local_error($id, 'E_BACKEND', $message);
	}
	close $socket;

	unless (defined $response) {
		return _local_error($id, 'E_BACKEND',
			'csf-ui-helper closed the connection without responding');
	}
	unless (ref($response) eq 'HASH' && exists $response->{ok}) {
		return _local_error($id, 'E_BACKEND', 'csf-ui-helper returned a malformed response');
	}
	# Section 3.1: exactly one request per connection, and this client makes
	# exactly one. A response whose id does not match what was sent cannot be
	# trusted to belong to this call.
	if (defined $response->{id} && "$response->{id}" ne "$id") {
		return _local_error($id, 'E_BACKEND', 'csf-ui-helper returned a mismatched response id');
	}

	return $response;
}

sub _local_error {
	my ($id, $code, $message) = @_;
	return { id => $id, ok => 0, error => $code, message => $message };
}

###############################################################################
# _connect($path, $deadline) -> ($socket, undef, undef) | (undef, $kind, $why)
#
# A non-blocking connect, bounded by $deadline, with an explicit SO_ERROR
# check once the descriptor is writable - not IO::Socket::UNIX's own
# Timeout option. Measured directly: passing Timeout to IO::Socket::UNIX's
# constructor returned a "connected" socket for every one of several
# over-backlog attempts against a listener that was not accepting, so
# whatever internal wait it performs does not reliably detect that a
# non-blocking AF_UNIX connect has not actually completed. A writable
# descriptor after a non-blocking connect() means only that the kernel has
# an answer ready, not that the answer is success - SO_ERROR is what says
# which.
#
# $kind distinguishes two different meanings section 3.5 already has: 'busy'
# for a connect that never resolved before $deadline (the reachable
# full-backlog state above, matching E_BUSY's transient/retry meaning
# exactly), and 'unavailable' for everything else - no such socket,
# permission denied, or an explicit connection refusal (E_UNAVAILABLE's
# existing meaning here).
###############################################################################
sub _connect {
	my ($path, $deadline) = @_;

	socket(my $sock, Socket::PF_UNIX(), Socket::SOCK_STREAM(), 0)
		or return (undef, 'unavailable', "socket: $!");

	my $flags = fcntl($sock, Fcntl::F_GETFL(), 0);
	unless (defined $flags) {
		close $sock;
		return (undef, 'unavailable', "fcntl: $!");
	}
	unless (fcntl($sock, Fcntl::F_SETFL(), $flags | Fcntl::O_NONBLOCK())) {
		close $sock;
		return (undef, 'unavailable', "fcntl: $!");
	}

	my $sockaddr = eval { Socket::pack_sockaddr_un($path) };
	unless (defined $sockaddr) {
		close $sock;
		return (undef, 'unavailable', 'the socket path is not valid for AF_UNIX');
	}

	unless (connect($sock, $sockaddr)) {
		unless ($!{EINPROGRESS} || $!{EWOULDBLOCK}) {
			close $sock;
			return (undef, 'unavailable', "connect: $!");
		}

		my $left = $deadline - Time::HiRes::time();
		if ($left <= 0) {
			close $sock;
			return (undef, 'busy', 'connect did not complete within the timeout');
		}
		my $win = '';
		vec($win, fileno($sock), 1) = 1;
		my $wout = $win;
		my $ready = select(undef, $wout, undef, $left);
		unless ($ready) {
			close $sock;
			return (undef, 'busy', 'connect did not complete within the timeout');
		}

		my $err = getsockopt($sock, Socket::SOL_SOCKET(), Socket::SO_ERROR());
		if (defined $err) {
			my $errno = unpack('i', $err);
			if ($errno != 0) {
				close $sock;
				local $! = $errno;
				return (undef, 'unavailable', "connect: $!");
			}
		}
	}

	# Back to blocking mode: _write_all() below and Proto::read_message()
	# each implement their own select()-based deadline and expect a
	# blocking descriptor once connected, the same as every other socket
	# operation in this tier.
	fcntl($sock, Fcntl::F_SETFL(), $flags);
	return ($sock, undef, undef);
}

# Bounded by $deadline, never by a blocking write with no ceiling. Mirrors
# the select()-then-syswrite shape csf-ui-helper itself uses for its own
# response write (write_response()) and that ConfigServer::UI::Proto uses for
# reads (read_message()) - the same non-signal, select-based style
# throughout, rather than mixing in alarm()-based timeouts that would have to
# coexist with whatever signal handling the surrounding web tier sets up.
sub _write_all {
	my ($socket, $line, $deadline) = @_;
	my $written = 0;
	while ($written < length $line) {
		my $left = $deadline - Time::HiRes::time();
		return 0 if $left <= 0;

		my $win = '';
		vec($win, fileno($socket), 1) = 1;
		my $wout = $win;
		my $ready = select(undef, $wout, undef, $left);
		next if !defined $ready || $ready == 0;

		my $wrote = syswrite($socket, $line, length($line) - $written, $written);
		unless (defined $wrote) {
			next if $!{EINTR};
			return 0;
		}
		return 0 if $wrote <= 0;
		$written += $wrote;
	}
	return 1;
}

1;
